# NumPy

## Завдання 1
* Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
* Збережіть масив у змінну і виведіть його на екран.
* Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
* Відсортуйте масив за зростанням і виведіть результат.
* Відобразіть масив до і після сортування.

In [1]:
# pip install numpy

In [2]:
import numpy as np

In [3]:
rand10 = np.random.randint(0, 100, size=10)
rand10

array([63, 19, 92, 74, 83, 23, 43,  1, 36, 91], dtype=int32)

In [4]:
print("мінімальне: %d, максимальне %d та середнє значення масиву %f" % (
    np.min(rand10), 
    np.max(rand10), 
    np.mean(rand10)
))

мінімальне: 1, максимальне 92 та середнє значення масиву 52.500000


In [5]:
print(rand10, np.sort(rand10), sep='\n')

[63 19 92 74 83 23 43  1 36 91]
[ 1 19 23 36 43 63 74 83 91 92]


## Завдання 2
* Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
* Виведіть масив у читабельному вигляді (у вигляді таблиці).
* Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
* Визначте загальне середнє значення масиву.
* Виведіть усі результати в зручному вигляді
(наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").

In [6]:
rand_4_4 = np.random.randint(1, 20, size=(4,4))
rand_4_4

array([[ 3,  4, 16, 10],
       [16,  8, 19, 10],
       [ 4,  5, 17,  1],
       [ 2,  4, 18,  1]], dtype=int32)

In [7]:
print(np.sum(rand_4_4, axis=0),  # columns
      np.sum(rand_4_4, axis=1),  # rows
      np.mean(rand_4_4))

[25 21 70 22] [33 53 27 25] 8.625


In [14]:
print(*["%s | %d" % (k,v) for (k,v) in 
        zip(rand_4_4, np.sum(rand_4_4, axis=1))], 
      "-----------------",
      np.sum(rand_4_4, axis=0), sep='\n', end=' | ')
print(np.mean(rand_4_4))

[ 3  4 16 10] | 33
[16  8 19 10] | 53
[ 4  5 17  1] | 27
[ 2  4 18  1] | 25
-----------------
[25 21 70 22] | 8.625
